version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.production
        volumes:
            - ./production-app-data:/data
            - ./keys/server.pfx:/server.pfx
            - ~/.aspnet/https:/root/.aspnet/https:ro
            - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
        environment:
            LANG: ja_JP.UTF-8
            TZ: Asia/Tokyo
            ASPNETCORE_ENVIRONMENT: Production
            PROTOCOL: HTTPS
            ASPNETCORE_Kestrel__Certificates__Default__Password: password
            ASPNETCORE_Kestrel__Certificates__Default__Path: /server.pfx
            TITLE: "Health Report"
            MAIL_SUBJECT: 健康フォローアップ用健康観察データの報告
            TIMEFRAME: "午前 00:00:00-11:59:59; 午後 12:00:00-23:59:59"
            # SUBDIR: "/ncvc"
            # LDAP_REGEX_STAFF: ^c0000[0-9]{5}$
            # LDAP_HOST: uni-ldap1.db.tokushima-u.ac.jp
            # LDAP_PORT: 636
            # LDAP_BASE: dc=tokushima-u,dc=ac,dc=jp
            # LDAP_ID_ATTR: uid
            # LDAP_NAME_ATTR: displayName;lang-ja
        networks:
            - ncvc
        depends_on:
            - db
        cap_add:
            - SYS_ADMIN
     
    db:
        image: postgres:latest
        ports:
            - 5432:5432
        volumes:
            - ./production-db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ncvc
            POSTGRES_PASSWORD: password
            POSTGRES_DB: ncvc_production
            TZ: Asia/Tokyo
        networks:
            - ncvc

networks:
    ncvc:
        driver: bridge
