version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        volumes:
            - app-data:/data
        environment:
            LANG: ja_JP.UTF-8
            TZ: Asia/Tokyo
            ASPNETCORE_ENVIRONMENT: Development
            PROTOCOL: HTTP
            TITLE: "Health Report (development)"
            MAIL_SUBJECT: 健康フォローアップ用健康観察データの報告
            TIMEFRAME: "午前 00:00:00-11:59:59; 午後 12:00:00-23:59:59"
            DAYS_TO_SEARCH: 365

        networks:
            - ncvc
        depends_on:
            - db
        cap_add:
            - SYS_ADMIN
     
    db:
        image: postgres:latest
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ncvc
            POSTGRES_PASSWORD: password
            POSTGRES_DB: ncvc_development
            TZ: Asia/Tokyo
        networks:
            - ncvc


volumes:
    app-data:
        driver: local
    db-data:
        driver: local


networks:
    ncvc:
        driver: bridge
