version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.production.http
        ports:
            - 80:8080
        volumes:
            - ./production-app-data:/data
        environment:
            LANG: ja_JP.UTF-8
            TZ: Asia/Tokyo
            ASPNETCORE_ENVIRONMENT: Production
            PROTOCOL: HTTP
            TITLE: "Health Report (http)"
            TIMEFRAME: "午前 00:00:00-11:59:59; 午後 12:00:00-23:59:59"
            DAYS_TO_SEARCH: 365

        networks:
            - ncvc
        depends_on:
            - db
        cap_add:
            - SYS_ADMIN
     
    db:
        image: postgres:latest
        ports:
            - 5432:5432
        volumes:
            - ./production-db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ncvc
            POSTGRES_PASSWORD: password
            POSTGRES_DB: ncvc_production
            TZ: Asia/Tokyo
        networks:
            - ncvc


networks:
    ncvc:
        driver: bridge
